<div class="clearfix"></div>
<div class="container">
	<div id="bparticle" class="tocfy" data-toc-side="right" data-toc-position="fixed">	
		<h2>Open Data Client</h2>
		<p>The Open Data Client is a module that helps you to show and provide Open Data.</p>
		<p>You can share google spreadsheets or local csv files.</p>
		<p>Files:</p>
		<code>
application/<br>
&nbsp;&nbsp;--- libraries/BP_Opendataclient.php<br>
&nbsp;&nbsp;--- controllers/Json.php	<br>
&nbsp;&nbsp;--- controllers/Opendataclient.php<br>
		</code>
		<br>
		<p><b>BP_Opendataclient.php</b> and <b>Json.php</b> are the two main files, don't thouch them unless you know what are you doing. The <b>Opendataclient.php</b> file is a template to create any controller you want to make the job.</p>
		<p>To share your Opendata see the structure of the example controller: Opendataclient.php</p>
		<h3>Just <label class="label-success">&nbsp;2&nbsp;</label> steps to show data</h3>
		<ul>
		<li>
		At the top of your controller create a public configuration array called <code>$opendata</code>:
		<pre><code>
public $opendata = array(
	"source"=>'gs', //values:gs|local
	"mode"=>'', //values: view|download|both, only for gs source
	"sheetId"=>'a_long_sheet_id_by_google' //the id of google sheet or a path to local files	
);
		</code></pre>
		</li>
		<li>
		Call the function to create opendata:
<pre><code>
$od=$this->createOpendata();		
</code>	</pre>
		</li>
		</ul>
		<p>
		As ususal for any codeIgniter based app, push the result to view:
<pre><code>$toView["opendata"] = $od;
$this->content=$this->load->view("pages/mypage",$toView,true);</code></pre>
		</p>
		<p>Then just print the <code>$opendata</code> variable in your view.</p>
		<p class="text-success">Important: the way Opendataclient prints the code is compatible with <a href="automatictoc">Automatic Toc:<code>.tocfy</code></a> and <a href="automatictabs">Automatic Tabs: <code>.tabfy</code></a> helpers.</p>
		<h3>The configuration array</h3>
		<pre>
Values:
source: gs|local
	gs -> points to a public google drive spreadsheed
	local -> points to a local folder (default: data/opendata/) and parses all csv files inside
 
mode: has different options in function of source
	gs->view|download|''(empty) 
		view: shows data, 
		download: shows links for download,
		'': leave empty to have both in one page
	
	local->''|filename
		'': leave empty to parse all csv in a directory
		filename: the complete filename (e.g. myfile.csv) you want to parse
	
sheetId: 
 	if gs: the google sheet Id, 
 	if local: the directory where you store files. 
		Leave empty to point to the default directory (data/opendata/). 
		Otherwise add a local path (must be readable).			
		</pre>
		<h3>Examples</h3>
		<p>Se here some examples:</p>
		<small>Generated by example*() functions in the Opendataclient.php template controller.</small>
		<ul>
		<li><a href="<?php echo uri_string();?>/example">Example 1</a>: google spreadsheet full (tables and download links) data source page</li>
		<li><a href="<?php echo uri_string();?>/example2">Example 2</a>: google spreadsheet download data source page</li>
		<li><a href="<?php echo uri_string();?>/example3">Example 3</a>: local data source single CSV page</li>
		<li><a href="<?php echo uri_string();?>/example4">Example 4</a>: local data source all CSV page</li>
		</ul>
	</div>
</div>

